#!/bin/zsh

function _dotfiles_init_functions() {
  echo "[dotfiles] initialising functions"

  # clear init.zsh
  if [[ -e "$DOTFILES_HOME/zsh/functions/init.zsh" ]]; then
    truncate -s 0 "$DOTFILES_HOME/zsh/functions/init.zsh"
  else
    touch "$DOTFILES_HOME/zsh/functions/init.zsh"
  fi

  # in init.zsh: add function directories to fpath
  echo "fpath=($(echo $(find "$DOTFILES_HOME/zsh/functions" -type d)) \"\${fpath[@]}\")" >> "$DOTFILES_HOME/zsh/functions/init.zsh"

  # load function to compile files
  source $DOTFILES_HOME/zsh/functions/dotfiles/_dotfiles_compile_file

  for function_file in $(find "$DOTFILES_HOME/zsh/functions" -type f ! -name "*.*"); do
    # in init.zsh: autoload function
    echo "autoload -Uz $function_file" >> "$DOTFILES_HOME/zsh/functions/init.zsh"

    # compile function
    echo "[dotfiles] compiling $function_file"
    _dotfiles_compile_file $function_file
  done

  # compile init file
  _dotfiles_compile_file "$DOTFILES_HOME/zsh/functions/init.zsh"

  echo "[dotfiles] functions initialised"
}
